import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { ThemeProvider } from "@/components/ThemeProvider";
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";
import "highlight.js/styles/github-dark.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="max-w-3xl mx-auto p-4 dark:bg-gray-900 dark:text-gray-100">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* 여기에 헤더 추가 */}
          <header className="border-b py-4 mb-8 flex justify-between items-center">
            <h1 className="text-xl font-bold">DevLog</h1>
            <nav className="flex items-center gap-4">
              <a href="/" className="mr-4">Home</a>
              <a href="/about">About</a>
              <ThemeToggle/>
            </nav>
          </header>
          {/* children = 내가 만들 main 페이지 들어가는 곳 */}
          <main>
            {children}
          </main>
          {/** footer 추가 */}
          <footer className="border-t py-4 mt-10 text-center text-gray-500 text-sm">
            © 2025 Vorschlag Tech Blog
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
